baseurl = "/"
DefaultContentLanguage = "de"
title = "Wöbking"

enableRobotsTXT = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[languages]
  [languages.de]
    locale = "de_DE"
    weight = 1

[menu]
  [[menu.main]]
    title = "Unternehmen"
    identifier = "home"
    weight = 100
    url = "/"
  [[menu.main]]
    title = "Katalog"
    identifier = "catalog"
    weight = 200
    url = "http://www.1kserver.com/preview/75ee8c875238aaad4df4a6529fadc82c5150736a/"
    external = true

