baseurl = "/"
DefaultContentLanguage = "de"
title = "Wöbking GmbH"

enableRobotsTXT = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.de]
    locale = "de_DE"
    weight = 1

[menu]
  [[menu.main]]
    title = "Unternehmen"
    identifier = "home"
    weight = 100
    url = "/"
  [[menu.main]]
    title = "Katalog"
    identifier = "catalog"
    weight = 200
    url = "/katalog"
    external = true

